// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcqdsaCmG1Cecmdjk_2ibfCxrkXx5LMc',
    appId: '1:8364199906:web:665726d3182c4d63eff3bb',
    messagingSenderId: '8364199906',
    projectId: 'doantotnghiep-e31d2',
    authDomain: 'doantotnghiep-e31d2.firebaseapp.com',
    databaseURL: 'https://doantotnghiep-e31d2-default-rtdb.firebaseio.com',
    storageBucket: 'doantotnghiep-e31d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UI7jofApcfxALaAwaJG-rWuig9ELw6A',
    appId: '1:8364199906:android:7346994ef1b63f62eff3bb',
    messagingSenderId: '8364199906',
    projectId: 'doantotnghiep-e31d2',
    databaseURL: 'https://doantotnghiep-e31d2-default-rtdb.firebaseio.com',
    storageBucket: 'doantotnghiep-e31d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-SmPEnivVvihrxEibgGU2JV-uBZq8C8',
    appId: '1:8364199906:ios:c2ffa5ca8b738fceeff3bb',
    messagingSenderId: '8364199906',
    projectId: 'doantotnghiep-e31d2',
    databaseURL: 'https://doantotnghiep-e31d2-default-rtdb.firebaseio.com',
    storageBucket: 'doantotnghiep-e31d2.appspot.com',
    iosBundleId: 'com.example.doAnTotNghiep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpcqdsaCmG1Cecmdjk_2ibfCxrkXx5LMc',
    appId: '1:8364199906:web:77c8499dacfe096feff3bb',
    messagingSenderId: '8364199906',
    projectId: 'doantotnghiep-e31d2',
    authDomain: 'doantotnghiep-e31d2.firebaseapp.com',
    databaseURL: 'https://doantotnghiep-e31d2-default-rtdb.firebaseio.com',
    storageBucket: 'doantotnghiep-e31d2.appspot.com',
  );
}
